@startuml
'https://plantuml.com/class-diagram

interface WordRanker {
    + getRankedWords(String text): Map<String, Integer>
}

class WordRankerImpl implements WordRanker {
    - filter: WordFilter
    + getRankedWords(String text): Map<String, Integer>
}

interface WordFilter {
    + isAvoidable(String word): boolean
}

WordRankerImpl -> WordFilter

@enduml